### ISSUE TITLE
CheckJson CRITICAL: key check failed: unexpected value for key: 'true' != 'true'

### ISSUE THREAD

**Issue by cmattoon** [sensu-plugins/sensu-plugins-http#18]
The plugin checks for string values, but JSON may contain boolean or integer values. For example, the object `{"health": true, "errors": 0}` would fail for `--key "errors" --value "0"` and `--key "health" --value "true"`. 

I notice that this works in [sensu-community-plugins/http/check-http-json.rb](https://github.com/sensu/sensu-community-plugins/blob/master/plugins/http/check-http-json.rb), which handles nested values as well. I'm submitting a patch for the string comparison, but will hold off on nested values for now. Is there a reason for the difference?

**Comment by mattyjones** [comment]
@cmattoon I am unsure of the reason for the difference personally.

**Comment by eheydrick** [comment]
This was fixed in PR https://github.com/sensu-plugins/sensu-plugins-http/pull/19.
