### ISSUE TITLE
Support passing headers

### ISSUE THREAD

**Issue by runningman84** [sensu-plugins/sensu-plugins-http#22]
I would like to do requests like
curl -I -v -A test -H "X-Forwarded-Proto: https" -H "Host: www.example.com" http://127.0.0.1/
Passing headers is not supported by check-http right now :/

**Comment by mattyjones** [comment]
I would not be against this if we coded it properly. Do you have time @runningman84 ?

**Comment by eheydrick** [comment]
@runningman84 ping.

**Comment by runningman84** [comment]
I will add this to my (rather long) todo list

**Comment by majormoses** [comment]
@runningman84 this can be closed right? It looks like its available in `check-http.rb`

**Comment by runningman84** [comment]
yes
