### ISSUE TITLE
create new release for latest HEAD

### ISSUE THREAD

**Issue by oryband** [sensu-plugins/sensu-plugins-http#23]
the latest release, 0.1.2 is missing some features from master/HEAD, `--method` to name a few

**Comment by eheydrick** [comment]
There are some issues with the build that need to be resolved then we can cut a new release. Looks like rest-client is missing as a dep.

**Comment by oryband** [comment]
indeed, screws up my checks. any chance to fix this quickly since we already know the solution?

**Comment by oryband** [comment]
@eheydrick **UPDATE:** i have successfully used `check-http-json.rb` from HEAD without any mofications (specifically didn't add `require 'rest-client'`) and it's working perfectly.

**Comment by analytically** [comment]
Why would we fix a version that's not the latest?

**Comment by oryband** [comment]
@analytically this is the latest commit (HEAD) according to today. I've successfully used the above script without using `rest-client` as a dependency. I have not checked the other scripts.

**Comment by eheydrick** [comment]
I meant a runtime dependency on rest-client in the gemspec. I just added that (https://github.com/sensu-plugins/sensu-plugins-http/commit/e3e3bc7bd209aa9260c31b7855b4f40604c9c6fb) and now the build is succeeding. I want to rename http-json-graphite.rb to conform to the naming scheme and then we can cut a new release.

**Comment by analytically** [comment]
Sounds good!

**Comment by oryband** [comment]
let's do this. i'm waiting for you.

**Comment by analytically** [comment]
Let's wait for @eheydrick to do his renames.

**Comment by eheydrick** [comment]
[0.2.0](https://rubygems.org/gems/sensu-plugins-http/versions/0.2.0) has been released. Thanks for your patience!

**Comment by oryband** [comment]
thank you! :)
