### ISSUE TITLE
please document post usage

### ISSUE THREAD

**Issue by raviteja59** [sensu-plugins/sensu-plugins-http#31]
Hi matty, 
it would be quite helpful if you could post he usage of these plugins.

Thanks
razer

**Comment by virtualdxs** [comment]
Yes. Documentation is a good thing. Please document this.

**Comment by coolgooze** [comment]
I am trying to execute the following, 
check-http.rb '--noproxy -u http://<ServerAddress>/<someurl>  -t 60 -P 8080'

i get the error
Invalid check argument(s): invalid option: --noproxy -u http://<ServerAddress>/<someurl> -t 60 -P 8080, ["/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/mixlib-cli-1.5.0/lib/mixlib/cli.rb:191:in `parse_options'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:13:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:55:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:55:in `block in <class:CLI>'"]


hence, i am wondering whats expected by the plugin

**Comment by eheydrick** [comment]
@coolgooze Remove the quotes around the options. The command should look like:

`check-http.rb --noproxy -u http://some.site.com/blah  -t 60 -P 8080`

**Comment by eheydrick** [comment]
I added a few usage examples to check-http.

https://github.com/sensu-plugins/sensu-plugins-http/blob/master/bin/check-http.rb#L18-L29

**Comment by zeushammer** [comment]
Could you please show an example of a POST using json data with multiple headers? I seem unable to get the syntax down correct.

**Comment by majormoses** [comment]
@zeushammer can you show us your example that is not working?

**Comment by majormoses** [comment]
@zeushammer 
something like this should work looking at the code:
```
$ bundle exec ./bin/check-http.rb -u https://httpbin.org/post --method POST --header 'Origin: ma.local.box, SomeRandomHeader: foo' --body '{"foo": "bar"}' 
CheckHttp OK: 200, 532 bytes
```

Can you validate something like this works for you? If so I can document that.

**Comment by majormoses** [comment]
could some of the people who needed help check out #75 which aims to help users grok how to use it.

**Comment by majormoses** [comment]
I am gonna consider this closed based on what I released here: https://rubygems.org/gems/sensu-plugins-http/versions/2.3.0 if you have questions feel free to re-open or open a new one.
