### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by absolutejam** [sensu-plugins/sensu-plugins-http#49]
Hi,

I'm trying to download and build the gem by using either `sensu-install -p http` or `/opt/sensu/embedded/bin/gem install sensu-plugins-http` and I'm getting the following errors:

![mstsc_2016-08-05_14-19-15](https://cloud.githubusercontent.com/assets/6817942/17437767/9253bc26-5b17-11e6-91f2-e7156abf8e71.png)

Any ideas how I can resolve this?

Kind regards,
James.

**Comment by eheydrick** [comment]
Looks like you are missing development tools. Try installing `build-essential` or the equivalent for your distro. `rest-client` and `aws-sdk` dependencies require a compiler to install.

**Comment by absolutejam** [comment]
Thanks for that! All working now :)
