### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by ttarczynski** [sensu-plugins/sensu-plugins-http#53]
I need a new release with 074f514 included.

In version 1.0.0 `sensu-plugins-http` is the only sensu plugin that depends on `'rest-client', '~> 2.0'`.

I build (automatically with fpm) RPM packages of all needed sensu gems (plugins and dependencies).
And the `'rest-client', '~> 2.0'` dependency conflicts with other plugins `'rest-client',    '1.8.0'`.

**Comment by eheydrick** [comment]
2.0.0 is out on rubygems.
