### ISSUE TITLE
incorrect metrics output metrics-curl.rb

### ISSUE THREAD

**Issue by zanoubia** [sensu-plugins/sensu-plugins-http#54]
Hi,
Original output of curl contains a comma 
Thus using ',' as split separator causes confusion and incorrect metrics.
It must be changed :
curl -w "%{time_total}|%{time_namelookup}|%{time_connect}|%{time_pretransfer}|%{time_redirect}|%{time_starttransfer}|%{http_code}" "http://localhost/index.php?action=Login"
0,038|0,004|0,005|0,005|0,000|0,038|301

**Comment by majormoses** [comment]
This is probably locale specific issue which we need to solve, when I have some time I will review your PR in greater depth but am not sure this would work for other LOCALEs. What LOCALE do you have set?
