### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by basickarl** [sensu-plugins/sensu-plugins-http#61]
A list with the dependencies in the documentation would be very... very helpful.

**Comment by eheydrick** [comment]
While we don't have the dependencies explicitly listed out in the docs, you can always see the gem dependencies in the gemspec. e.g. https://github.com/sensu-plugins/sensu-plugins-http/blob/master/sensu-plugins-http.gemspec#L33-L35. Were you looking for something beyond that? We're in the process of revamping the docs in all the plugins and we'll take that into consideration.
