### ISSUE TITLE
Allow override of http status codes.

### ISSUE THREAD

**Issue by aatchison** [sensu-plugins/sensu-plugins-http#89]
Hello,

I am writing some health checks for Vault, and find this plugin to be very useful. I do however have to need to check json values, even if the http status code returned is not 200. For Vault specifically,  a 429 is perfectly valid and has meaning of it's own.

I have a solution here, would this be acceptable? It simply gives the option to override failure if the code is not 200. This is a workable solution for me, but I would love your feedback.
https://github.com/aatchison/sensu-plugins-http/commit/5e0998ff0e69eeba956440f144012920f5525694#diff-6ba3638df2b4a2aa90beb376dc703d4eR179
https://github.com/aatchison/sensu-plugins-http/tree/allow-override-http-status-code

Thanks

Arron

**Comment by majormoses** [comment]
> For Vault specifically, a 429 is perfectly valid and has meaning of it's own.

As in a rate limit? I will take a look but I think 429 should be considered `unknown` as its not able to retrieve the actual status. We can also allow specifying list of OK status codes.

**Comment by majormoses** [comment]
So it turns out I already reviewed this (without the context), short answer is yes this is reasonable path forward overall. To avoid the same conversations in both places I will respond further on the PR.

**Comment by majormoses** [comment]
Actually I am gonna treat them as two separate things to solve:
- allowing multiple status codes
- better defaults for `429`

The multiple statuses are being addressed through the PR but I would like to continue the conversation on the defaults for a `429`. I think unless its specifically passed as an expected response code it should be an `unknown`. My rationale for this is that outside of [vault's use case](https://www.vaultproject.io/api/index.html#http-status-codes) I have only seen `429` to indicate rate limiting. I certainly understand that in most cases being rate limited may not be an actionable alert I think that it does indicate an issue and should not silently sit there with no indication of being rate limited.

**Comment by majormoses** [comment]
Added in #99 and released in https://rubygems.org/gems/sensu-plugins-http/versions/2.11.0 it allow specifying codes via regex. for example `

If you feel this did not solve your request please reply back and we can take abother look at it.
