### ISSUE TITLE
Allow alternate response codes

### ISSUE THREAD

**Issue by chrisbaldauf** [sensu-plugins/sensu-plugins-http#9]
I have a use case where I have a `/healthcheck` route that returns a json hash containing the status of each major external component that the system talks to. My desire is to setup a `check-http-json` check for each of the three components of the app so that I can know at a glance where the issue might be. The trouble that I'm running into is that my /healthcheck route returns a 200 if everything is healthy and a 503 otherwise. This results in all of my checks going critical if any of them fail. I'd like to be able to ignore the response code with a `--ignore-respose-code` parameter (or similar). 

```
$ curl http://127.0.0.1/healthcheck -v
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /healthcheck HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
* Server nginx/1.8.0 is not blacklisted
< Server: nginx/1.8.0
< Date: Mon, 27 Jul 2015 18:43:10 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: Express
< 
* Connection #0 to host 127.0.0.1 left intact
{
  "generated_at": "2015-07-27T18:43:08.837Z",
  "duration_millis": "0.3",
  "tests": {
    "db": {
      "test_name": "db",
      "tested_at": "2015-07-27T18:43:08.837Z",
      "duration_millis": "3.4",
      "result": "passed"
    },
    "redis": {
      "test_name": "redis",
      "tested_at": "2015-07-27T18:43:08.837Z",
      "result": "failed",
      "duration_millis": "999.9",
      "error": "timeout"
    },
    "statsd": {
      "test_name": "statsd",
      "tested_at": "2015-07-27T18:43:08.837Z",
      "result": "passed",
      "duration_millis": "1.0"
    }
  }
}
```
Notice that redis.result === "failed" and db and statsd.result === "passed"

Given that `/healthcheck` output, I'd like to setup the following checks and have deploymenttracker-http and deploymenttracker-redis be critical and -statsd and -db be OK.
```
{
  "checks": {
    "deploymenttracker-http": {
      "type": "check",
      "handlers": ["default"],
      "command": "/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/http/check-http.rb -t 10 -u http://localhost/healthcheck",
      "interval": 30,
      "standalone": true
    },
    "deploymenttracker-db": {
      "type": "check",
      "handlers": ["default"],
      "command": "/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/http/check-http-json.rb -t 10 -u http://localhost/healthcheck --key \"tests,db,result\" --value \"passed\"",
      "interval": 30,
      "standalone": true
    },
    "deploymenttracker-redis": {
      "type": "check",
      "handlers": ["default"],
      "command": "/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/http/check-http-json.rb -t 10 -u http://localhost/healthcheck --key \"tests,redis,result\" --value \"passed\"",
      "interval": 30,
      "standalone": true
    },
    "deploymenttracker-statsd": {
      "type": "check",
      "handlers": ["default"],
      "command": "/opt/sensu/embedded/bin/ruby /etc/sensu/plugins/http/check-http-json.rb -t 10 -u http://localhost/healthcheck --key \"tests,statsd,result\" --value \"passed\"",
      "interval": 30,
      "standalone": true
    }
  }
}
```

Would you be open to a PR adding a `--ignore-status-code` parameter that would alter the code flow to not return critical with the code if `--ignore-status-code` was asserted? If you have suggestions for a better parameter name or different implementation, I'd be happy to hear them. https://github.com/sensu/sensu-community-plugins/blob/master/plugins/http/check-http-json.rb#L101

Thanks for your consideration!

**Comment by mattyjones** [comment]
@chrisbaldauf  I am always open to PR's :)

I think adding a flag is the best idea in IMHO and I see no issues atm with merging it.

**Comment by chrisbaldauf** [comment]
Awesome. I'm away from my computer today, but I'll get something submitted
in the next couple of days. Thanks!

**Comment by eheydrick** [comment]
@chrisbaldauf how's it going with adding that flag?

**Comment by chrisbaldauf** [comment]
Hey, sorry for the radio silence. It turned out that we were using an old version of the check in question, which I patched in place on my system. I can post the code that I added if you think it will help, but it doesn't match up with the current version of the plugin.
